### ISSUE TITLE
REI server error

### ISSUE THREAD

**Issue by DankyJohnson** [Siphalor/spiceoffabric#57]
Minecraft 1.19
spiceoffabric-1.5.3+1.19
fabric-api-0.58.0+1.19

The server won't start. I have uploaded the latest.log, here is the important part:

> Caused by: java.lang.RuntimeException: Failed to initialize REI entry point: me.shedaniel.rei.RoughlyEnoughItemsCore
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:88) ~[RoughlyEnoughItems-9.1.517.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-9.1.517.jar:?]
	at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198) ~[?:?]
	at com.sun.proxy.jdk.proxy3.$Proxy37.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
	... 7 more
**Caused by: java.lang.RuntimeException: Rerached side issue when loading REI plugin by Spice of Fabric. Please use "rei_server", "rei_client" or "rei_common" instead.**
	at me.shedaniel.rei.RoughlyEnoughItemsState.error(RoughlyEnoughItemsState.java:53) ~[RoughlyEnoughItems-9.1.517.jar:?]
	at me.shedaniel.rei.fabric.PluginDetectorImpl.loadPlugin(PluginDetectorImpl.java:107) ~[RoughlyEnoughItems-9.1.517.jar:?]
	at me.shedaniel.rei.fabric.PluginDetectorImpl.detectCommonPlugins(PluginDetectorImpl.java:136) ~[RoughlyEnoughItems-9.1.517.jar:?]
	at me.shedaniel.rei.PluginDetector.detectCommonPlugins(PluginDetector.java) ~[RoughlyEnoughItems-9.1.517.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsCore.onInitialize(RoughlyEnoughItemsCore.java:153) ~[RoughlyEnoughItems-9.1.517.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.initializeEntryPoint(RoughlyEnoughItemsInitializer.java:84) ~[RoughlyEnoughItems-9.1.517.jar:?]
	at me.shedaniel.rei.RoughlyEnoughItemsInitializer.onInitialize(RoughlyEnoughItemsInitializer.java:48) ~[RoughlyEnoughItems-9.1.517.jar:?]
	at java.lang.invoke.MethodHandleProxies$1.invoke(MethodHandleProxies.java:198) ~[?:?]
	at com.sun.proxy.jdk.proxy3.$Proxy37.onInitialize(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.8.jar:?]
	... 7 more

[latest.log](https://github.com/Siphalor/spiceoffabric/files/9212207/latest.log)

**Comment by anthony-mariotti** [comment]
Also, client-side for non-server gameplay:

![image](https://user-images.githubusercontent.com/48564383/184450456-b41d8c69-001c-4986-9f5d-022fdceda6b0.png)
