### ISSUE TITLE
Crash randomly after eating.

### ISSUE THREAD

**Issue by HySand** [Siphalor/spiceoffabric#76]
Minecraft 1.19.2
Eating food causes error code and kick player from server randomly.
<details>

```
[13:43:18] [Netty Client IO #5/ERROR]: Encountered exception while handling in channel with name "spiceoffabric:add_food"
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 32 out of bounds for int[20]
	at java.lang.System.arraycopy(Native Method) ~[?:?]
	at de.siphalor.spiceoffabric.util.FixedLengthIntFIFOQueue.setLength(FixedLengthIntFIFOQueue.java:135) ~[spiceoffabric-1.6.0-beta.2+1.19.2.jar:?]
	at de.siphalor.spiceoffabric.foodhistory.FoodHistory.addFood(FoodHistory.java:245) ~[spiceoffabric-1.6.0-beta.2+1.19.2.jar:?]
	at de.siphalor.spiceoffabric.client.SoFClient.lambda$onInitializeClient$2(SoFClient.java:41) ~[spiceoffabric-1.6.0-beta.2+1.19.2.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:106) ~[fabric-networking-api-v1-1.2.10+10eb22f490-20034e2fa80ac40b.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:42) ~[fabric-networking-api-v1-1.2.10+10eb22f490-20034e2fa80ac40b.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) [fabric-networking-api-v1-1.2.10+10eb22f490-20034e2fa80ac40b.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:98) [fabric-networking-api-v1-1.2.10+10eb22f490-20034e2fa80ac40b.jar:?]
	at net.minecraft.class_634.handler$ckb000$handleCustomPayload(class_634.java:3022) [client-intermediary.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) [client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:60) [client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:8) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:167) [client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:152) [client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:50) [client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[13:43:18] [Netty Client IO #5/ERROR]: Exception occurred in netty pipeline
java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 32 out of bounds for int[20]
	at java.lang.System.arraycopy(Native Method) ~[?:?]
	at de.siphalor.spiceoffabric.util.FixedLengthIntFIFOQueue.setLength(FixedLengthIntFIFOQueue.java:135) ~[spiceoffabric-1.6.0-beta.2+1.19.2.jar:?]
	at de.siphalor.spiceoffabric.foodhistory.FoodHistory.addFood(FoodHistory.java:245) ~[spiceoffabric-1.6.0-beta.2+1.19.2.jar:?]
	at de.siphalor.spiceoffabric.client.SoFClient.lambda$onInitializeClient$2(SoFClient.java:41) ~[spiceoffabric-1.6.0-beta.2+1.19.2.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:106) ~[fabric-networking-api-v1-1.2.10+10eb22f490-20034e2fa80ac40b.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.receive(ClientPlayNetworkAddon.java:42) ~[fabric-networking-api-v1-1.2.10+10eb22f490-20034e2fa80ac40b.jar:?]
	at net.fabricmc.fabric.impl.networking.AbstractChanneledNetworkAddon.handle(AbstractChanneledNetworkAddon.java:101) ~[fabric-networking-api-v1-1.2.10+10eb22f490-20034e2fa80ac40b.jar:?]
	at net.fabricmc.fabric.impl.networking.client.ClientPlayNetworkAddon.handle(ClientPlayNetworkAddon.java:98) ~[fabric-networking-api-v1-1.2.10+10eb22f490-20034e2fa80ac40b.jar:?]
	at net.minecraft.class_634.handler$ckb000$handleCustomPayload(class_634.java:3022) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11152(class_634.java) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11457(class_2658.java:60) ~[client-intermediary.jar:?]
	at net.minecraft.class_2658.method_11054(class_2658.java:8) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10759(class_2535.java:167) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.method_10770(class_2535.java:152) ~[client-intermediary.jar:?]
	at net.minecraft.class_2535.channelRead0(class_2535.java:50) ~[client-intermediary.jar:?]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:314) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:435) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) [netty-codec-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) [netty-handler-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) [netty-transport-4.1.77.Final.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) [netty-common-4.1.77.Final.jar:?]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.77.Final.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```
</details>

**Comment by HySand** [comment]
Mod list
<details>

```
        - advanced_runtime_resource_pack 0.6.2 via enhancedblockentities
	- amecsapi 1.3.6+mc22w17a via backslot
	- appleskin 2.4.1+mc1.19
	- architectury 6.4.62
	- backslot 1.2.11
	- balm-fabric 4.5.2+0
	- bclib 2.1.5
	- betteranimationscollection 4.0.5
	- bettercombat 1.5.4+1.19
	- betterend 2.1.2
	- betternether 7.1.2
	- blur 2.6.0
	- bobby 4.0.1
	- bookshelf 16.2.16
	- cameraoverhaul 1.4.0-fabric-universal
	- cardinal-components-base 5.0.2 via puzzleslib
	- cardinal-components-block 5.0.2 via puzzleslib
	- cardinal-components-chunk 5.0.2 via puzzleslib
	- cardinal-components-entity 5.0.2 via puzzleslib
	- cardinal-components-world 5.0.2 via puzzleslib
	- charm 4.4.4
	- chat_heads 0.9.0
	- chatsounds 1.1.7
	- chunksfadein 3.0.7-1.19
	- cloth-api 4.0.65
	- cloth-basic-math 0.6.1 via cloth-api
	- cloth-client-events-v0 4.0.65 via cloth-api
	- cloth-common-events-v1 4.0.65 via cloth-api
	- cloth-config 8.2.88
	- cloth-scissors-api-v1 4.0.65 via cloth-api
	- cloth-utils-v1 4.0.65 via cloth-api
	- coat 1.0.0-beta.18+mc22w17a via spiceoffabric
	- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
	- com_github_llamalad7_mixinextras 0.1.1 via porting_lib_base
	- com_github_luben_zstd-jni 1.5.2-2 via dashloader
	- com_google_code_findbugs_jsr305 3.0.2 via create
	- com_logisticscraft_occlusionculling 0.0.6-SNAPSHOT via entityculling
	- com_moandjiezana_toml_toml4j 0.7.2 via charm
	- com_typesafe_config 1.4.2 via bobby
	- combatroll 1.1.2+1.19
	- comforts 6.0.3+1.19.2
	- continuity 2.0.1+1.19
	- create 0.5.0g-796+1.19.2
	- create_crystal_clear 1.0+1.19.2
	- dashloader 4.1.3+1.19
	- dev_quantumfusion_hyphen 0.2.2 via dashloader
	- dev_quantumfusion_taski 1.1.0 via dashloader
	- dramaticdoors 1.19.2-1.3.5_1
	- dripstone_fluid_lib 2.0.1 via milk
	- droplight 1.0.5
	- enchant_giver 1.3.0 via mcdw
	- enchdesc 13.0.14
	- enhancedblockentities 0.7.2+1.19.2
	- entityculling 1.5.2-mc1.19
	- error_notifier 1.0.9 via roughlyenoughitems
	- fabric-api 0.72.0+1.19.2
	- fabric-api-base 0.4.14+6e0787e690 via fabric-api
	- fabric-api-lookup-api-v1 1.6.13+93d8cb8290 via fabric-api
	- fabric-biome-api-v1 9.1.0+82db024a90 via fabric-api
	- fabric-block-api-v1 1.0.2+e415d50e90 via fabric-api
	- fabric-blockrenderlayer-v1 1.1.23+c6af733c90 via fabric-api
	- fabric-client-tags-api-v1 1.0.4+b35fea8390 via fabric-api
	- fabric-command-api-v1 1.2.15+f71b366f90 via fabric-api
	- fabric-command-api-v2 2.2.0+413cbbc790 via fabric-api
	- fabric-commands-v0 0.2.32+df3654b390 via fabric-api
	- fabric-containers-v0 0.1.40+df3654b390 via fabric-api
	- fabric-content-registries-v0 3.5.0+7c6cd14d90 via fabric-api
	- fabric-convention-tags-v1 1.2.1+27265b3490 via fabric-api
	- fabric-crash-report-info-v1 0.2.8+aeb40ebe90 via fabric-api
	- fabric-data-generation-api-v1 5.3.6+413cbbc790 via fabric-api
	- fabric-dimensions-v1 2.1.34+0d0f210290 via fabric-api
	- fabric-entity-events-v1 1.5.3+9244241690 via fabric-api
	- fabric-events-interaction-v0 0.4.33+562bff6e90 via fabric-api
	- fabric-events-lifecycle-v0 0.2.33+df3654b390 via fabric-api
	- fabric-game-rule-api-v1 1.0.24+b6b6abb490 via fabric-api
	- fabric-item-api-v1 1.6.3+9785ec3590 via fabric-api
	- fabric-item-groups-v0 0.3.37+9244241690 via fabric-api
	- fabric-key-binding-api-v1 1.0.25+5c4fce2890 via fabric-api
	- fabric-keybindings-v0 0.2.23+df3654b390 via fabric-api
	- fabric-language-kotlin 1.9.0+kotlin.1.8.0
	- fabric-lifecycle-events-v1 2.2.3+1b46dc7890 via fabric-api
	- fabric-loot-api-v2 1.1.11+83a8659290 via fabric-api
	- fabric-loot-tables-v1 1.1.14+9e7660c690 via fabric-api
	- fabric-message-api-v1 5.0.6+93d8cb8290 via fabric-api
	- fabric-mining-level-api-v1 2.1.22+33fbc73890 via fabric-api
	- fabric-models-v0 0.3.20+c6af733c90 via fabric-api
	- fabric-networking-api-v1 1.2.10+10eb22f490 via fabric-api
	- fabric-networking-v0 0.3.27+df3654b390 via fabric-api
	- fabric-object-builder-api-v1 4.1.5+9785ec3590 via fabric-api
	- fabric-particles-v1 1.0.13+4d0d570390 via fabric-api
	- fabric-recipe-api-v1 1.0.0+413cbbc790 via fabric-api
	- fabric-registry-sync-v0 0.9.31+9244241690 via fabric-api
	- fabric-renderer-api-v1 1.2.0+2e5408b590 via fabric-api
	- fabric-renderer-indigo 0.7.0+2e5408b590 via fabric-api
	- fabric-renderer-registries-v1 3.2.23+df3654b390 via fabric-api
	- fabric-rendering-data-attachment-v1 0.3.18+6e0787e690 via fabric-api
	- fabric-rendering-fluids-v1 3.0.10+4d0d570390 via fabric-api
	- fabric-rendering-v0 1.1.26+df3654b390 via fabric-api
	- fabric-rendering-v1 1.12.0+08b73de490 via fabric-api
	- fabric-resource-conditions-api-v1 2.1.2+aae9039d90 via fabric-api
	- fabric-resource-loader-v0 0.8.3+251d254a90 via fabric-api
	- fabric-screen-api-v1 1.0.31+4d0d570390 via fabric-api
	- fabric-screen-handler-api-v1 1.3.6+1cc24b1b90 via fabric-api
	- fabric-sound-api-v1 1.0.2+c4f28df590 via fabric-api
	- fabric-textures-v0 1.0.23+aeb40ebe90 via fabric-api
	- fabric-transfer-api-v1 2.1.5+413cbbc790 via fabric-api
	- fabric-transitive-access-wideners-v1 1.3.3+08b73de490 via fabric-api
	- fabricloader 0.14.12
	- fake-player-api 0.5.0 via create
	- fallingleaves 1.13.0+1.19.2
	- farmersdelight 1.19.2-1.3.9
	- fiber 0.23.0-2 via patchouli
	- flywheel 0.6.8-1 via create
	- forge_tags 3.0 via porting_lib
	- forgeconfigapiport 4.2.10
	- ftbchunks 1902.3.14-build.218
	- ftblibrary 1902.3.11-build.166
	- ftbteams 1902.2.11-build.87
	- highlighter 1.1.4
	- iceberg 1.0.46
	- indium 1.0.9+mc1.19.2
	- ingameime 1.6.6
	- io_github_douira_glsl-transformer 2.0.0-pre8 via iris
	- io_leangen_geantyref_geantyref 1.3.13 via bobby
	- iris 1.5.0
	- jade 8.7.0
	- jadeaddons 3.0.0
	- java 17
	- kirin 1.11.1 via presencefootsteps
	- lambdabettergrass 1.3.0+1.19
	- lazydfu 0.1.3
	- mcda 2.2.0
	- mcdw 5.0.4-1.19
	- memoryleakfix 1.19.3-0.7.0
	- midnightlib 0.5.2 via blur
	- milk 1.0.51 via create
	- minecraft 1.19.2
	- mm 2.3 via porting_lib_base
	- modmenu 4.1.2
	- moonlight 1.19.2-2.1.24
	- morechathistory 1.1.1
	- nimble 3.0.0
	- noindium 1.1.0+1.19 via create
	- notenoughanimations 1.6.2
	- org_anarres_jcpp 1.4.14 via iris
	- org_antlr_antlr4-runtime 4.11.1 via iris
	- org_javassist_javassist 3.28.0-GA via yungsapi
	- org_jetbrains_kotlin_kotlin-reflect 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.5 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.1 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.1 via fabric-language-kotlin
	- org_joml_joml 1.10.4 via sodium
	- org_reflections_reflections 0.10.2 via yungsapi
	- org_spongepowered_configurate-core 4.1.2 via bobby
	- org_spongepowered_configurate-hocon 4.1.2 via bobby
	- patchouli 1.19.2-77-FABRIC
	- pickupnotifier 4.2.0
	- plasmo_voice 1.2.19
	- player-animator 0.4.0
	- porting_lib 2.1.623+1.19.2 via create
	- porting_lib_accessors 2.1.623+1.19.2 via porting_lib_extensions
	- porting_lib_attributes 2.1.623+1.19.2 via porting_lib_extensions
	- porting_lib_base 2.1.623+1.19.2 via porting_lib
	- porting_lib_common 2.1.623+1.19.2 via porting_lib_extensions
	- porting_lib_constants 2.1.623+1.19.2 via porting_lib_attributes
	- porting_lib_entity 2.1.623+1.19.2 via porting_lib
	- porting_lib_extensions 2.1.623+1.19.2 via porting_lib_transfer
	- porting_lib_lazy_registration 2.1.623+1.19.2 via porting_lib
	- porting_lib_model_generators 2.1.623+1.19.2 via porting_lib
	- porting_lib_model_loader 2.1.623+1.19.2 via porting_lib_obj_loader
	- porting_lib_models 2.1.623+1.19.2 via porting_lib
	- porting_lib_networking 2.1.623+1.19.2 via porting_lib
	- porting_lib_obj_loader 2.1.623+1.19.2 via porting_lib
	- porting_lib_transfer 2.1.623+1.19.2 via porting_lib
	- presencefootsteps 1.6.4
	- prism 1.0.3
	- puzzleslib 4.3.12
	- reach-entity-attributes 2.3.0 via create
	- registrate-fabric 1.1.44-MC1.19.2 via create
	- rottencreatures 1.0.1
	- roughlyenoughitems 9.1.580
	- satin 1.8.0 via blur
	- serialization_hooks 0.3.26 via porting_lib_base
	- skinlayers 1.5.2-mc1.19.1
	- smoothswapping 0.6
	- sodium 0.4.4+build.18
	- sound_physics_remastered 1.19.2-1.0.18
	- spectrelib 0.10.0+1.19 via comforts
	- spiceoffabric 1.6.0-beta.2+1.19.2
	- spruceui 4.0.0+1.19 via lambdabettergrass
	- supplementaries 1.19.2-2.2.34b
	- talkbubbles 1.0.4
	- tectonic 1.1.3
	- travelerstitles 1.19.2-Fabric-3.1.0
	- treechop 0.17.0
	- tweed4_annotated 1.3.1+mc22w17a via spiceoffabric
	- tweed4_base 1.7.1+mc22w17a via spiceoffabric
	- tweed4_data 1.2.1+mc22w17a via spiceoffabric
	- tweed4_data_hjson 1.1.1+mc22w17a via spiceoffabric
	- tweed4_tailor_coat 1.1.3+mc22w17a via spiceoffabric
	- tweed4_tailor_screen 1.1.1+mc22w17a via spiceoffabric
	- visuality 0.5.5
	- waystones 11.1.0
	- yungsapi 1.19.2-Fabric-3.8.2
```
</details>

**Comment by McKitten** [comment]
Dito but it only seems to happen on the first login ~90% of the time.
I have modified the config but that was due to the combination of origins and this mod only giving me 6 (60% of 14?) health to start with.
No crash report but 
Internal Exception : java.lang.ArrayIndexOutOfBoundsException: arraycopy: last destination index 20 out of bounds for int[5]
after being booted back to menu.

**Comment by C-Higgins** [comment]
@Siphalor Could you push a release for this fix?
